jobsNamespace: platform-jobs

platform:
  clusterName: default
  apiUrl: http://platform-api:8080/api/v1
  authUrl: http://platform-auth:8080
  configUrl: http://platform-config:8080
  registryUrl: https://registry-dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

podAnnotations:
  iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-366c09e4841fcc83df56b8f070c34716

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [monitoring-dev.neu.ro]
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_MONITORINGAPI_SESSION

cors:
  origins:
  - http://localhost:8000
  - https://master--neuro-web.netlify.app
  - https://master--megafon-web.netlify.app
  - https://master--mts-web.netlify.app
  - https://master--minzdrav-web.netlify.app

fluentd:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClassName: standard

  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-366c09e4841fcc83df56b8f070c34716

logs:
  persistence:
    type: aws
    aws:
      region: us-east-1
      bucket: neuro-job-logs-dev

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
