image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

containerRuntime:
  port: 9000

replicas: 2

jobsNamespace: platform-jobs

kubeletPort: 10250
nvidiaDCGMPort:

platform:
  clusterName: ""
  apiUrl: https://api.apolo.us
  appsUrl: https://api.apolo.us
  authUrl: https://api.apolo.us
  configUrl: https://api.apolo.us
  registryUrl: ""
  token: {}

resources:
  requests:
    cpu: "0.1"
    memory: "50Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

secrets: []

podAnnotations: {}

sentry:
  dsn: ""
  clusterName: ""
  appName: platform-monitoring
  sampleRate: 0.002

nodeLabels:
  nodePool: platform.neuromation.io/nodepool

fluentbit:
  nameOverride: fluent-bit
  fullnameOverride: fluent-bit
  image:
    repository: ghcr.io/neuro-inc/fluent-bit
    tag: "2.1.10"
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 128Mi
  tolerations:
    - effect: NoSchedule
      operator: Exists
  podAnnotations: {}
  taildb:
    directory: /var/lib/platform-monitoring-fluent-bit
  logLevel: info
  containerRuntime:
    name: containerd # docker, cri-o

logs:
  cleanup_interval_sec: 900

  compact:
    podAnnotations: {}

    resources:
      requests:
        cpu: "0.1"
        memory: "128Mi"
      limits:
        cpu: "0.3"
        memory: "512Mi"

  persistence:
    type: loki # Possible values: es, s3, loki

    keySecret: ""

    # es:
    #   host: elasticsearch
    #   port: 9200

    # s3:
    #   region: us-east-1
    #   accessKeyId: {} # optional
    #   secretAccessKey: {} # optional
    #   bucket: logs
    #   endpoint: ""

    # loki:
    #   endpoint: http://loki-gateway
    #   archiveDelay: "5" # 5 seconds
    #   retentionPeriodS: "7776000" # 90 days

priorityClassName: ""
