jobsNamespace: platform-jobs

platform:
  clusterName: default
  apiUrl: http://platform-api:8080/api/v1
  authUrl: http://platform-auth:8080
  configUrl: http://platform-config:8080
  registryUrl: https://registry-dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

containerRuntime:
  name: containerd

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [monitoring-dev.neu.ro]
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_MONITORINGAPI_SESSION

cors:
  origins:
  - '*'

fluentd:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClassName: standard

logs:
  persistence:
    type: gcp

    keySecret: gcp-key

    gcp:
      project: development-374312
      location: us-central1
      bucket: neuro-dev-logs

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002

priorityClassName: ""
