jobsNamespace: platform-jobs

platform:
  clusterName: default
  apiUrl: http://platform-api:8080
  authUrl: http://platform-auth:8080
  configUrl: http://platform-config:8080
  registryUrl: https://registry-dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

containerRuntime:
  name: containerd

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [monitoring-dev.neu.ro]
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_MONITORINGAPI_SESSION

logs:
  persistence:
    type: s3

    s3:
      region: minio
      accessKeyId:
        valueFrom:
          secretKeyRef:
            name: minio-gateway
            key: root-user
      secretAccessKey:
        valueFrom:
          secretKeyRef:
            name: minio-gateway
            key: root-password
      endpoint: http://minio-gateway:9000
      bucket: neuro-dev-logs

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002

priorityClassName: platform-services
