image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

containerRuntime:
  name: docker # containerd, cri-o
  port: 9000

replicas: 2

jobsNamespace: default

kubeletPort: 10250
nvidiaDCGMPort:

platform:
  clusterName: ""
  authUrl: https://staging.neu.ro
  configUrl: https://staging.neu.ro
  apiUrl: https://staging.neu.ro/api/v1
  registryUrl: ""
  token: {}

resources:
  requests:
    cpu: "0.1"
    memory: "50Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

secrets: []

podAnnotations: {}

cors:
  origins: []

zipkin: {}

sentry: {}

nodeLabels:
  job: platform.neuromation.io/job
  nodePool: platform.neuromation.io/nodepool

fluentbit:
  nameOverride: fluent-bit
  fullnameOverride: fluent-bit
  image:
    repository: ghcr.io/neuro-inc/fluent-bit
    tag: "2.1.10"
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 128Mi
  tolerations:
    - effect: NoSchedule
      operator: Exists
  podAnnotations: {}
  taildb:
    directory: /var/lib/platform-monitoring-fluent-bit
  logLevel: info

minioGateway:
  nameOverride: minio-gateway
  fullnameOverride: minio-gateway
  image:
    repository: ghcr.io/neuro-inc/minio
    # minio gateway was removed from minio, we need to stick to old minio version
    tag: RELEASE.2022-03-08T22-28-51Z
  port: 9000
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  podAnnotations: {}

logs:
  cleanup_interval_sec: 900

  compact:
    podAnnotations: {}

    resources:
      requests:
        cpu: "0.1"
        memory: "128Mi"
      limits:
        cpu: "0.3"
        memory: "512Mi"

  persistence:
    type: es

    keySecret: ""

    es:
      host: elasticsearch
      port: 9200

    # aws:
    #   accessKeyId: access_key # optional
    #   secretAccessKey: access_key # optional
    #   region: us-east-1
    #   bucket: logs
    #   endpoint: ""
    #   forcePathStyle: false

    # gcp:
    #   serviceAccountKeyBase64:
    #   project: project
    #   location: us
    #   bucket: logs

    # azure:
    #   storageAccountName: account_name
    #   storageAccountKey: account_key
    #   bucket: logs

    ## minio is for on_prem clusters which do not have
    ## any object storage service.
    ##
    # minio:
    #   url: http://minio:9000
    #   accessKey: access_key
    #   secretKey: secret_key
    #   region: region
    #   bucket: logs

priorityClassName: ""
