FROM python:3.6.6-stretch

WORKDIR /neuromation

ARG PIP_INDEX_URL

# installing dependencies ONLY
COPY setup.py ./
RUN \
    pip install -e . && \
    pip uninstall -y platform-mon

# installing platform-api
COPY platform_mon platform_mon
RUN pip install -e .

ENV NP_API_PORT=8080
EXPOSE $NP_API_PORT

CMD platform-mon