apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformMonitoring.fullname" . }}
  labels:
    {{- include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: platform-monitoring
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformMonitoring.name" . }}
      release: {{ .Release.Name }}
      service: platform-monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformMonitoring.name" . }}
        release: {{ .Release.Name }}
        service: platform-monitoring
      annotations:
      {{- if or .Values.annotations .Values.secrets }}
      annotations:
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.secrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: platform-monitoring
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: tcp-web
            protocol: TCP
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          {{- include "platformMonitoring.env.common" . | nindent 10 }}
          {{- if eq .Values.logs.persistence.type "es" }}
          - name: NP_MONITORING_LOGS_STORAGE_TYPE
            value: elasticsearch
          - name: NP_MONITORING_ES_HOSTS
          {{- with .Values.logs.persistence.es }}
            value: "http://{{ .host }}:{{ .port }}"
          {{- end }}
          {{- else if eq .Values.logs.persistence.type "s3" }}
          {{- include "platformMonitoring.env.s3" . | indent 10 }}
          {{- else if eq .Values.logs.persistence.type "loki" }}
          {{- include "platformMonitoring.env.loki" . | indent 10 }}
          {{- end }}
        volumeMounts:
          {{- include "platformMonitoring.volumeMounts.common" . | nindent 10 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
        {{- include "platformMonitoring.volumes.common" . | nindent 8 }}
