{{- $configPattern := "files/fluent-bit/*" }}
{{- $config := tpl (.Files.Glob $configPattern).AsConfig . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluent-bit
data:
{{ $config | indent 2 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluent-bit
spec:
  selector:
    matchLabels:
      app: {{ include "platformMonitoring.name" . }}
      release: {{ .Release.Name | quote }}
      service: fluent-bit
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: {{ include "platformMonitoring.name" . }}
        release: {{ .Release.Name | quote }}
        service: fluent-bit
      annotations:
        checksum/config: {{ $config | sha256sum }}
    spec:
      containers:
      - image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
        name: fluent-bit
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        {{- if eq .Values.containerRuntime.name "docker" }}
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        {{- end }}
        - name: tail-db
          mountPath: /tail-db
{{- range $path, $_ := .Files.Glob $configPattern }}
        - name: config
          mountPath: /fluent-bit/etc/{{ base $path }}
          subPath: {{ base $path }}
{{- end }}
{{- if .Values.fluentbit.resources }}
        resources:
{{ toYaml .Values.fluentbit.resources | indent 10 }}
{{- end }}
      volumes:
      - name: tail-db
        hostPath:
          path: {{ .Values.fluentbit.taildb.directory }}
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log
          type: ""
      {{- if eq .Values.containerRuntime.name "docker" }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
          type: ""
      {{- end }}
      - name: config
        configMap:
          name: fluent-bit-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeLabels.job | quote }}
                operator: Exists
{{- if .Values.fluentbit.tolerations }}
      tolerations:
{{ toYaml .Values.fluentbit.tolerations | indent 8 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
