{{- $configPattern := "files/fluent-bit/*" }}
{{- $config := tpl (.Files.Glob $configPattern).AsConfig . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platformMonitoring.fluentbit.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluent-bit
data:
{{ $config | indent 2 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "platformMonitoring.fluentbit.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluent-bit
spec:
  selector:
    matchLabels:
      app: {{ include "platformMonitoring.name" . }}
      release: {{ .Release.Name | quote }}
      service: fluent-bit
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: {{ include "platformMonitoring.name" . }}
        release: {{ .Release.Name | quote }}
        service: fluent-bit
      annotations:
        checksum/config: {{ $config | sha256sum }}
{{- if .Values.fluentbit.podAnnotations }}
{{ toYaml .Values.fluentbit.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: fluent-bit
        {{- with .Values.fluentbit.image }}
        image: {{ .repository }}:{{ .tag }}
        {{- end }}
        env:
        {{- if eq .Values.logs.persistence.type "aws" }}
        {{- if .Values.logs.persistence.aws.accessKeyId }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: access_key_id
        {{- end }}
        {{- if .Values.logs.persistence.aws.secretAccessKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: secret_access_key
        {{- end }}
        {{- else if eq .Values.logs.persistence.type "minio" }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: secret_key
        {{- else if or (eq .Values.logs.persistence.type "gcp") (eq .Values.logs.persistence.type "azure") }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.s3proxy.identity }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.s3proxy.credential }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        {{- if eq .Values.containerRuntime.name "docker" }}
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        {{- end }}
        - name: tail-db
          mountPath: /tail-db
        {{- range $path, $_ := .Files.Glob $configPattern }}
        - name: config
          mountPath: /fluent-bit/etc/{{ base $path }}
          subPath: {{ base $path }}
        {{- end }}
        {{- if .Values.fluentbit.resources }}
        resources: {{ toYaml .Values.fluentbit.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: tail-db
        hostPath:
          path: {{ .Values.fluentbit.taildb.directory }}
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log
          type: ""
      {{- if eq .Values.containerRuntime.name "docker" }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
          type: ""
      {{- end }}
      - name: config
        configMap:
          name: {{ include "platformMonitoring.fluentbit.fullname" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeLabels.job | quote }}
                operator: Exists
      {{- if .Values.fluentbit.tolerations }}
      tolerations: {{ toYaml .Values.fluentbit.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
