{{- if ne .Values.logs.persistence.type "es" }}
{{- $config := tpl (.Files.Glob "files/fluentd/*").AsConfig . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platformMonitoring.fluentd.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluentd
data:
{{ $config | indent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformMonitoring.fluentd.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluentd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.fluentd.forwardPort }}
    targetPort: {{ .Values.fluentd.forwardPort }}
  selector:
    app: {{ include "platformMonitoring.name" . }}
    release: {{ .Release.Name | quote }}
    service: fluentd
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformMonitoring.fluentd.fullname" . }}-service
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluentd
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.fluentd.forwardPort }}
    targetPort: {{ .Values.fluentd.forwardPort }}
  selector:
    app: {{ include "platformMonitoring.name" . }}
    release: {{ .Release.Name | quote }}
    service: fluentd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "platformMonitoring.fluentd.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: fluentd
spec:
  replicas: 1
  serviceName: fluentd
  selector:
    matchLabels:
      app: {{ include "platformMonitoring.name" . }}
      release: {{ .Release.Name | quote }}
      service: fluentd
  template:
    metadata:
      labels:
        app: {{ include "platformMonitoring.name" . }}
        release: {{ .Release.Name | quote }}
        service: fluentd
      annotations:
        checksum/config: {{ $config | sha256sum }}
        checksum/logs-secret: {{ include (print $.Template.BasePath "/logs-storage-key-secret.yaml") . | sha256sum }}
{{- if .Values.fluentd.podAnnotations }}
{{ toYaml .Values.fluentd.podAnnotations | indent 8 }}
{{- end }}
    spec:
      # K8s Security Context for fluentd aggregator pods
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: fluentd
        image: {{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}
        volumeMounts:
        - name: config
          mountPath: /opt/bitnami/fluentd/conf
          readOnly: true
        - name: fluentd-buffer
          mountPath: /opt/bitnami/fluentd/logs/buffers
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /fluentd.healthcheck?json=%7B%22ping%22%3A+%22pong%22%7D
            port: 9880
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        {{- if .Values.fluentd.resources }}
        resources: {{ toYaml .Values.fluentd.resources | nindent 10 }}
        {{- end }}
        env:
        - name: FLUENTD_CONF
          value: fluentd.conf

        {{- if eq .Values.logs.persistence.type "aws" }}
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: access_key_id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: secret_access_key
        {{- end }}

      {{- if eq .Values.logs.persistence.type "gcp" }}
        - name: S3_ACCESS_KEY_ID
          value: minio_access_key
        - name: S3_SECRET_ACCESS_KEY
          value: minio_secret_key
      - name: minio
        image: {{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}
        args:
        - gateway
        - gcs
        - {{ .Values.logs.persistence.gcp.project | quote }}
        env:
        - name: MINIO_ROOT_USER
          value: minio_access_key
        - name: MINIO_ROOT_PASSWORD
          value: minio_secret_key
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /accounts/key_json
        volumeMounts:
        - name: gcs-credentials
          mountPath: /accounts
          readOnly: true
{{ include "platformMonitoring.minio.resources" . | indent 8 }}
{{ include "platformMonitoring.minio.probes" . | indent 8 }}
      {{- end }}

      {{- if eq .Values.logs.persistence.type "azure" }}
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: account_name
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: account_key
      - name: minio
        image: {{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}
        args:
        - gateway
        - azure
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: account_name
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: account_key
{{ include "platformMonitoring.minio.resources" . | indent 8 }}
{{ include "platformMonitoring.minio.probes" . | indent 8 }}
      {{- end }}

        {{- if eq .Values.logs.persistence.type "minio" }}
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: access_key
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
              key: secret_key
        {{- end }}

      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: {{ include "platformMonitoring.fluentd.fullname" . }}
      {{- if eq .Values.logs.persistence.type "gcp" }}
      - name: gcs-credentials
        secret:
          secretName: {{ include "platformMonitoring.logs.storage.keySecret" . }}
      {{- end }}
      {{- if not .Values.fluentd.persistence.enabled }}
      - name: fluentd-buffer
        emptyDir: {}
      {{- end }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}


  {{- if .Values.fluentd.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: fluentd-buffer
      spec:
        accessModes:
        - {{ .Values.fluentd.persistence.accessMode }}
        {{- if .Values.fluentd.persistence.storageClassName }}
        {{- if eq .Values.fluentd.persistence.storageClassName "-" }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.fluentd.persistence.storageClassName | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.fluentd.persistence.size }}
  {{- end }}
{{- end }}
