{{- if .Values.ingress.enabled }}
{{- $ingressApiIsStable := eq (include "k8s.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "k8s.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "k8s.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "k8s.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "platformMonitoring.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: platform-monitoring
  annotations:
    {{- if not $ingressSupportsIngressClassName }}
    kubernetes.io/ingress.class: traefik
    {{- end }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if $ingressSupportsIngressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/jobs
        {{- if $ingressSupportsPathType }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ include "platformMonitoring.fullname" $ }}
            port:
              name: http
          {{- else }}
          serviceName: {{ include "platformMonitoring.fullname" $ }}
          servicePort: http
          {{- end }}
  {{- end }}
{{- end }}
