{{- if .Values.ingress.enabled }}
apiVersion: {{ include "platformMonitoring.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "platformMonitoring.fullname" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: platform-monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/jobs
        backend:
          serviceName: {{ include "platformMonitoring.fullname" $ }}
          servicePort: http
  {{- end }}
{{- end }}
