{{- if and (ne .Values.logs.persistence.type "es") (not .Values.logs.persistence.keySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platformMonitoring.logs.storage.keySecret" . }}
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
data:
{{- with .Values.logs.persistence }}
{{- if eq .type "gcp" }}
  key_json: {{ .gcp.serviceAccountKeyBase64 | quote }}
{{- else if eq .type "aws" }}
  access_key_id: {{ .aws.accessKeyId | default "" | b64enc | quote }}
  secret_access_key: {{ .aws.secretAccessKey | default "" | b64enc | quote }}
{{- else if eq .type "azure" }}
  account_name: {{ .azure.storageAccountName | b64enc | quote }}
  account_key: {{ .azure.storageAccountKey | b64enc | quote }}
{{- else if eq .type "minio" }}
  access_key: {{ .minio.accessKey | b64enc | quote }}
  secret_key: {{ .minio.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
