{{- if ne .Values.logs.persistence.type "es" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformMonitoring.fullname" . }}-logs-compact
  labels: {{ include "platformMonitoring.labels.standard" . | nindent 4 }}
    service: platform-monitoring-logs-compact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "platformMonitoring.name" . }}
      release: {{ .Release.Name }}
      service: platform-monitoring-logs-compact
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformMonitoring.name" . }}
        release: {{ .Release.Name }}
        service: platform-monitoring-logs-compact
      {{- if .Values.podAnnotations }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: compact
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: [platform-monitoring-logs-compact]
        {{- if .Values.logs.compact.resources }}
        resources: {{ toYaml .Values.logs.compact.resources | nindent 10 }}
        {{- end }}
        env:
        {{- include "platformMonitoring.env.common" . | nindent 8 }}
        {{- include "platformMonitoring.env.s3" . | indent 8 }}
        - name: NP_LOG_LEVEL
          value: INFO
        volumeMounts:
        {{- include "platformMonitoring.volumeMounts.common" . | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
      {{- include "platformMonitoring.volumes.common" . | nindent 6 }}
{{- end }}
