version: 2.1

executors:
    python:
      docker:
        - image: circleci/python:3.6.6-stretch

defaults: &defaults
  executor: python
  working_directory: ~/platform-monitoring

orbs:
  codecov: codecov/codecov@1.0.4
  gcloud: circleci/gcp-cli@1.3.0
  k8s: circleci/kubernetes@0.3.0


jobs:

  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-python_3.6.6-{{ checksum "requirements/test.txt" }}
      - run:
          name: Setup venv
          command: |
            python -m venv venv

      - run:
          name: Installing dependencies
          command: |
            . venv/bin/activate
            pip install --upgrade pip==19.1.1
            make setup

      - save_cache:
          paths:
            - venv
          key: v2-dependencies-python_3.6.6-{{ checksum "requirements/test.txt" }}
      - run:
          name: Running Static Code Analysis
          command: |
            source venv/bin/activate
            make lint

      - run:
          name: Running Unit Tests
          command: |
            source venv/bin/activate
            make test_unit


      - codecov/upload:
          file: .coverage.xml
          flags: unit

      - k8s/install
      - gcloud/install
      - setup_remote_docker:
          version: 18.09.3

      - run:
          name: GKE Auth
          command: |
            make -s gke_login
      - run:
          name: Pull integration images
          command: |
            # docker-credential-gcloud still relies on Python 2.7,
            # thus we'd better pull testing images before we set up Python 3
            make gke_docker_pull_test

      - run:
          name: Running Kubernetes
          command: |
            # https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#before-upgrading
            #
            # MountPropagation feature is now beta. As a consequence, all
            # volume mounts in containers are now rslave on Linux by default.
            # To make this default work in all Linux environments the entire
            # mount tree should be marked as shareable, e.g. via mount
            # --make-rshared /. All Linux distributions that use systemd
            # already have the root directory mounted as rshared and hence
            # they need not do anything. In Linux environments without systemd
            # we recommend running mount --make-rshared / during boot before
            # docker is started.
            sudo mount --make-rshared /
            sudo mount --make-rshared /run
            sudo mount --make-rshared /var/lib/docker

            make start_k8s
            make test_k8s

      - run:
          name: Running Integration Tests
          command: |
            source venv/bin/activate
            make test_integration
#
#      - run:
#          name: Stopping Kubernetes
#          command: |
#            make clean_k8s
#          when: always

      - codecov/upload:
          file: .coverage.xml
          flags: integration

  gke_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            make build
      - run:
          name: GKE Auth
          command: |
            make -s gke_login
      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push
      - run:
          name: GKE Deploy
          command: |
            make gke_deploy

workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-dev

  dev:
    jobs:
      - test:
          context: org-dev
          filters:
            branches:
              only:
                - master
      - gke_deploy:
          context: org-dev
          requires:
            - test
          filters:
            branches:
              only:
                - master
