version: 2.1


executors:
    python:
      docker:
        - image: circleci/python:3.6.6-stretch


defaults: &defaults
  executor: python
  working_directory: ~/platform-monitoring


orbs:
  codecov: codecov/codecov@1.0.4
  gcloud: circleci/gcp-cli@1.3.0
  k8s: circleci/kubernetes@0.3.0


jobs:

  gke_deploy:
    <<: *defaults
    steps:
      - gcloud/install
      - k8s/install
      - setup_remote_docker:
          version: 18.09.3
      - checkout
      - run:
          name: Build image
          command: |
            make build_k8s
      - run:
          name: GKE Auth
          command: |
            make -s gke_login
      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push
      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy

  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-python_3.6.6-{{ checksum "requirements/test.txt" }}

      - run:
          name: Installing dependencies
          command: |
            python -m venv .env
            source .env/bin/activate
            python --version
            make setup
            pip install codecov==2.0.15

      - save_cache:
          paths:
            - ./.env
          key: v1-dependencies-python_3.6.6-{{ checksum "requirements/test.txt" }}

#      - run:
#          name: Running Static Code Analysis
#          command: |
#            . .env/bin/activate
#            make lint

      - run:
          name: Running Unit Tests
          command: |
            . .env/bin/activate
            make test_unit

      - codecov/upload:
          file: client/.coverage.xml
          flags: client

workflows:
  version: 2

  main:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - /release.*/

  dev:
    jobs:
      - test:
          context: org-dev
          filters:
            branches:
              only:
                - master
      - gke_deploy:
          context: org-dev
          requires:
            - test
          filters:
            branches:
              only:
                - master

  staging:
    jobs:
      - test:
          context: org-staging
          filters:
            branches:
              only:
                - /release.*/
      - gke_deploy:
          context: org-staging
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/

  prod:
    jobs:
      - test:
          context: org-prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /release.*/
      - gke_deploy:
          context: org-prod
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /release.*/
