version: 2.1


executors:
    python:
      docker:
        - image: circleci/python:3.6.6-stretch


defaults: &defaults
  executor: python
  working_directory: ~/platform-monitoring


jobs:

  gke_deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy

  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            pyenv install --debug 3.6.3
            pyenv local 3.6.3-debug

# below rule cleans out hiredis, this is due to circle ci issue, to be resolved by moving to dockerized test execution
      - run:
          name: Setting Up Python Virtual Environment
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -U pip
            make setup
            pip uninstall -y hiredis


      - run:
          name: Run Platform Tests
          command: |
            source venv/bin/activate
            make test_unit

workflows:
  version: 2


  main:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - /release.*/

  dev:
    jobs:
      - test:
          context: org-dev
          filters:
            branches:
              only:
                - master
      - gke_deploy:
          context: org-dev
          requires:
            - test
          filters:
            branches:
              only:
                - master

  staging:
    jobs:
      - test:
          context: org-staging
          filters:
            branches:
              only:
                - /release.*/
      - gke_deploy:
          context: org-staging
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/

  prod:
    jobs:
      - test:
          context: org-prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /release.*/
      - gke_deploy:
          context: org-prod
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /release.*/
