apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerengineapi
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  nginx.conf: |-
    user root root;
    error_log /dev/stderr;

    events {}

    http {
        access_log /dev/stdout;
        server {
            listen 2375;
            location / {
                proxy_pass http://unix:/var/run/docker.sock:/;
                proxy_buffering off;
            }
        }
    }
---