apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockerengineapi
spec:
  selector:
    matchLabels:
      service: dockerengineapi
  template:
    metadata:
      labels:
        service: dockerengineapi
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/dockerengineapi_configmap.yml") . | sha256sum }}'
    spec:
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: dockerengineapi
        image: nginx:latest
        ports:
        - containerPort: 2375
          hostPort: 2375
        volumeMounts:
        - name: nginx-conf
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: nginx-conf
        configMap:
          name: dockerengineapi
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
