apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockerengineapi
spec:
  selector:
    matchLabels:
      service: dockerengineapi
  template:
    metadata:
      labels:
        service: dockerengineapi
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/dockerengineapi_configmap.yml") . | sha256sum | quote }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeLabels.job | quote }}
                operator: Exists
      hostNetwork: true
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: dockerengineapi
        image: {{ .Values.dockerEngine.image.repository }}:{{ .Values.dockerEngine.image.tag }}
        ports:
        - containerPort: {{ .Values.dockerEngine.port }}
        volumeMounts:
        - name: nginx-conf
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: nginx-conf
        configMap:
          name: dockerengineapi
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
{{- include "platform-monitoring.imagePullSecrets" .Values.dockerEngine.image.pullSecrets | indent 6 }}
