{{- if ne .Values.logs.persistence.type "es" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-monitoring.logs.storage.key" . }}
  labels:
{{ include "platform-monitoring.labels.standard" . | indent 4 }}
data:
{{- with .Values.logs.persistence }}
{{- if eq .type "gcp" }}
  key.json: {{ .gcp.serviceAccountKeyBase64 | quote }}
{{- else if eq .type "aws" }}
  access_key_id: {{ .aws.access_key_id | default "" | b64enc | quote }}
  secret_access_key: {{ .aws.secret_access_key | default "" | b64enc | quote }}
{{- else if eq .type "azure" }}
  account_name: {{ .azure.storageAccountName | b64enc | quote }}
  account_key: {{ .azure.storageAccountKey | b64enc | quote }}
{{- else if eq .type "minio" }}
  access_key: {{ .minio.accessKey | b64enc | quote }}
  secret_key: {{ .minio.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}