apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platformmonitoringapi
spec:
  replicas: {{ .Values.NP_MONITORING_REPLICAS }}
  selector:
    matchLabels:
      service: platformmonitoringapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformmonitoringapi
    spec:
      containers:
      - name: platformmonitoringapi
        image: {{ .Values.IMAGE }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ .Values.NP_MONITORING_REQUESTS_CPU }}
            memory: {{ .Values.NP_MONITORING_REQUESTS_MEMORY }}
          limits:
            cpu: {{ .Values.NP_MONITORING_LIMITS_CPU }}
            memory: {{ .Values.NP_MONITORING_LIMITS_MEMORY }}
        env:
        - name: NP_MONITORING_PLATFORM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: platformservices-secret
              key: compute_token
        - name: NP_MONITORING_PLATFORM_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: platformservices-secret
              key: compute_token
        - name: NP_MONITORING_K8S_API_URL
          value: https://kubernetes.default:443
        - name: NP_MONITORING_K8S_AUTH_TYPE
          value: token
        - name: NP_MONITORING_K8S_CA_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NP_MONITORING_K8S_TOKEN_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: NP_MONITORING_PLATFORM_API_URL
          value: {{ .Values.NP_MONITORING_PLATFORM_API_URL }}
        - name: NP_MONITORING_PLATFORM_AUTH_URL
          value: {{ .Values.NP_MONITORING_PLATFORM_AUTH_URL }}
        - name: NP_MONITORING_ES_HOSTS
          value: {{ .Values.NP_MONITORING_ES_HOSTS }}
        - name: NP_MONITORING_K8S_NS
          value: {{ .Values.NP_MONITORING_K8S_NS }}
        - name: NP_MONITORING_REGISTRY_URL
          value: {{ .Values.NP_MONITORING_REGISTRY_URL }}
        - name: NP_CLUSTER_NAME
          value: {{ .Values.NP_CLUSTER_NAME }}
        - name: NP_MONITORING_K8S_KUBELET_PORT
          value: {{ .Values.NP_MONITORING_K8S_KUBELET_PORT | quote }}
        - name: NP_CORS_ORIGINS
          value: {{ printf "%s" (pluck .Values.global.env .Values.NP_CORS_ORIGINS | first | default .Values.NP_CORS_ORIGINS._default) }}
      {{- if .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
      imagePullSecrets:
        - name: {{ .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: platformmonitoringapi
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: platformmonitoringapi
