NP_MONITORING_CLUSTER_NAME: "default"
NP_MONITORING_PLATFORM_API_URL: http://platformapi:8080/api/v1
NP_MONITORING_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_MONITORING_PLATFORM_CONFIG_URL: http://platformconfig:8080
NP_MONITORING_K8S_NS: platform-jobs
NP_MONITORING_REGISTRY_URL: https://registry-dev.neu.ro
NP_MONITORING_K8S_KUBELET_PORT: ""
NP_CORS_ORIGINS: http://localhost:8000,https://master--neuro-web.netlify.app,https://master--megafon-web.netlify.app,https://master--mts-web.netlify.app,https://master--minzdrav-web.netlify.app

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

podAnnotations:
  iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

ingress:
  enabled: true
  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [monitoring-dev.neu.ro]

fluentd:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClassName: standard

  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

logs:
  persistence:
    type: aws
    aws:
      region: us-east-1
      bucket: neuro-job-logs-dev

sentry:
  dsn: https://11316dd021994d7085c50e86c2ae404c@o454648.ingest.sentry.io/5597106
  clusterName: dev
  sampleRate: 0.1
