IMAGE: ''
NP_MONITORING_REQUESTS_CPU: "0.1"
NP_MONITORING_LIMITS_CPU: "0.2"
NP_MONITORING_REQUESTS_MEMORY: "50Mi"
NP_MONITORING_LIMITS_MEMORY: "100Mi"
NP_MONITORING_REPLICAS: "2"
NP_MONITORING_PLATFORM_API_URL: http://platformapi:8080/api/v1
NP_MONITORING_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_MONITORING_ES_HOSTS: http://logging-elasticsearch:9200
NP_MONITORING_K8S_NS: default
NP_MONITORING_REGISTRY_URL: https://registry-dev.neu.ro
NP_CLUSTER_NAME: "default"
NP_MONITORING_K8S_KUBELET_PORT: ""
