monitoring:
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

fluentd:
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

logs:
  persistence:
    type: aws
    aws:
      region: us-east-1
      bucket: neuro-job-logs-dev
