NP_MONITORING_CLUSTER_NAME: "default"
NP_MONITORING_PLATFORM_API_URL: http://platformapi:8080/api/v1
NP_MONITORING_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_MONITORING_PLATFORM_CONFIG_URL: http://platformconfig:8080
NP_MONITORING_K8S_NS: platform-jobs
NP_MONITORING_REGISTRY_URL: https://registry-dev.neu.ro
NP_MONITORING_K8S_KUBELET_PORT: ""
NP_CORS_ORIGINS: http://localhost:8000,https://master--neuro-web.netlify.app,https://master--megafon-web.netlify.app,https://master--mts-web.netlify.app,https://master--minzdrav-web.netlify.app

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

ingress:
  enabled: true
  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [monitoring-dev.neu.ro]

fluentd:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClassName: standard

logs:
  persistence:
    type: azure
    azure:
      region: eastus
      bucket: neuro-job-logs-dev
      storageAccountName: "st4006d4f97475ef17167b"
      storageAccountKey: "RQVBHaqd4L+lWAPQXcuUC0sbonEARxN8PijYA4tRnWqAby0bFGmvBr8fzSnYJIBsEdwEiBPkvAg8HEEqfFU0zw=="
