name: Pre-commit auto-update
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: .python-version
    - name: Install pre-commit
      run: pip install -U pre-commit
    - name: Run pre-commit autoupdate
      run: pre-commit autoupdate
    - id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_PRIVATE_KEY }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.8
      with:
        token: ${{ steps.generate_token.outputs.token }}
        branch: update/pre-commit-autoupdate
        title: Auto-update pre-commit hooks
        commit-message: Auto-update pre-commit hooks
        labels: dependencies
        body: |
          Update versions of tools in pre-commit
          configs to latest version
